#!/bin/bash

echo "🔧 Quick CORS Fix for LeetTrack"
echo "==============================="
echo ""
echo "Your Vercel deployment: https://leettrack-dimmrp6ez-edward-tans-projects.vercel.app"
echo ""

# The specific CORS origins needed
CORS_ORIGINS="https://leettrack.app,https://www.leettrack.app,https://leettrack-dimmrp6ez-edward-tans-projects.vercel.app"

echo "📝 CORS origins to set:"
echo "   $CORS_ORIGINS"
echo ""

echo "🚀 To fix CORS on your EC2 backend server:"
echo ""
echo "1. SSH into your EC2 server:"
echo "   ssh ubuntu@your-ec2-server-ip"
echo ""
echo "2. Navigate to your backend directory and run:"
echo "   cd /path/to/leettrack/backend"
echo ""
echo "3. Update CORS configuration:"
echo "   sed -i '/^CORS_ORIGINS=/d' .env"
echo "   echo \"CORS_ORIGINS=$CORS_ORIGINS\" >> .env"
echo ""
echo "4. Restart backend service:"
echo "   sudo systemctl restart leettrack-backend"
echo ""
echo "5. Verify fix:"
echo "   curl -I https://api.leettrack.app/api/v1/learning-paths"
echo ""
echo "✅ After this fix, your frontend should work!"
echo ""
echo "🔄 Alternative one-liner (if you prefer):"
echo "   echo \"CORS_ORIGINS=$CORS_ORIGINS\" | sudo tee -a /path/to/leettrack/backend/.env && sudo systemctl restart leettrack-backend" 