"""Add review confidence and needs_rating fields

Revision ID: 965986606ac9
Revises: add_is_admin_to_users
Create Date: 2025-06-13 12:46:46.855037

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "965986606ac9"
down_revision = "add_is_admin_to_users"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_questions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("review_confidence", sa.String(length=20), nullable=True)
        )
        batch_op.add_column(sa.Column("needs_rating", sa.Boolean(), nullable=True))

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "is_admin",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("false"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "is_admin",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("false"),
        )

    with op.batch_alter_table("user_questions", schema=None) as batch_op:
        batch_op.drop_column("needs_rating")
        batch_op.drop_column("review_confidence")

    # ### end Alembic commands ###
